version: '3.5'

services:
  zkp:
    environment:
      HASH_TYPE: 'mimc'
    depends_on:
      - merkle-tree
      
  merkle-tree:
    environment:
      HASH_TYPE: 'mimc'

  truffle-nightlite:
    volumes:
      - ./zkp/node_modules/@eyblockchain/nightlite/contracts/mimc/MerkleTree.sol:/truffle/contracts/MerkleTree.sol:delegated
